CREATE TABLE Operator(
	ID					INT PRIMARY KEY NOT NULL,
	FirstName 			VARCHAR(100) NOT NULL,
	LastName 			VARCHAR(100) NULL,
	DateOfBirth			DATE NOT NULL,
	DroneLicense		INT NOT NULL,
	RescueEndorsement	BOOLEAN NOT NULL,
	Operations			INT NOT NULL
	);
	
CREATE TABLE Map(
	ID			INT PRIMARY KEY NOT NULL,
	Filename	VARCHAR(100) NOT NULL
	); 
    
CREATE TABLE Drone(
	ID			INT PRIMARY KEY NOT NULL,
	Name 		VARCHAR(100) NOT NULL,
	ClassType	INT NOT NULL,
	Rescue		BOOLEAN NOT NULL,
	OperatorID	INT NULL UNIQUE,
	MapID		INT NULL,
	FOREIGN KEY(OperatorID) REFERENCES Operator(ID),
	FOREIGN KEY(MapID) REFERENCES Map(ID)
	);